name: fetch-latest

on:
  push:
    branches:
      - gh-pages
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

permissions:
  contents: write

env:
  SHEET_ID: ${{ secrets.SHEET_ID }}
  GC_KEY_JSON: ${{ secrets.GC_KEY_JSON }}
  GOOGLE_APPLICATION_CREDENTIALS: "gc-credentials.key.json"

jobs:
  fetch-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'gh-pages'
      - name: dependencies
        run: npm ci
      - name: auth key
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "gc-credentials.key.json"
          json: ${{ secrets.GC_KEY_JSON }}
      - name: fetch sheet data
        run: npm run fetch
      - name: git config
        uses: ./.github/actions/git-config
      - name: ghpages deploy
        run: |
          if [[ `git status --porcelain` ]]; then
            git add -A
            git commit -m 'Automated data fetch'
            git push
          else
            echo "Nothing to commit"
          fi
        shell: bash

