name: Production

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  GC_KEY_JSON: ${{ secrets.GC_KEY_JSON }}
  GOOGLE_APPLICATION_CREDENTIALS: "./.gc.key.json"

jobs:
  Production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: dependencies
        run: npm ci
      - name: auth key
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: ".gc.key.json"
          json: ${{ secrets.MY_JSON }}
      # - name: GC Key
      #   run: |
      #     touch .gc.key.json
      #     echo \'${{ secrets.GC_KEY_JSON }}\' >> .gc.key.json
      - name: fetch sheet data
        run: npm run fetch
      - name: git config
        uses: ./.github/actions/git-config
      - name: ghpages deploy
        run: |
          git add -A
          git commit -m 'Automated data fetch'
          git push origin gh-pages -f

