name: Production

on:
  push:
    branches:
      - main

permissions:
  contents: write

# env:
  # DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
  Production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Git config
        uses: ./.github/actions/git-config
      # - name: Dotenv config
      #   run: |
      #     touch .env
      #     echo DISCORD_WEBHOOK=\"${{ secrets.DISCORD_WEBHOOK }}\" >> .env
      - name: Dependencies
        run: npm ci
      - name: Fetch Sheet Data
        run: npm run fetch
      - name: Git push
        run: |
          git add -A
          git commit -m 'Automated data fetch'
          git push origin gh-pages -f

